version: 5.1.0      # 配置文件版本
variant: default    # Icarus 主题变体，可选 "default" 或 "cyberpunk"
logo: /images/logo.png      # 网站 Logo 的路径或 URL
# 页面元数据配置
head:
    favicon: /images/logo.png
    manifest:
        name: Lucy Wisteria's Blog
        short_name: Lucy's Blog         # 当没有足够空间显示全名时，显示的应用短名称
        start_url: /                    # Web 应用的起始 URL
        theme_color: '#ffffff'          # 应用的默认主题颜色
        background_color: '#ffffff'     # 应用页面在样式表加载前显示的背景颜色占位符
        display: standalone             # 网站的首选显示模式
        icons:                          # 网站图标列表
            -
                src: '/images/logo.png'
                sizes: ''
                type: 'image/png'
    # Open Graph 元数据
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: Lucy Wisteria's Blog
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    # 页面结构化数据
    structured_data:
        title: 
        description: 
        url: 
        author: Lucy Wisteria
        publisher: Lucy Wisteria
        publisher_logo: '/images/logo.png'
        image: 
    # 其他 HTML 元标签数组
    meta:
        # 元标签按 <属性>=<值> 格式指定
        # 例如：name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # 网站 RSS atom.xml 的 URL 或路径
    rss: 
    - <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=ZCOOL+XiaoWei&display=swap">
    - <link rel="stylesheet" href="/blog/css/custom.css">
# 页面顶部导航栏配置
navbar:
    # 导航菜单项
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
    # 显示在导航栏右侧的链接
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/wsh-zju/blog
# 页脚配置
footer:
    # 版权文本
    copyright: © 2026- Lucy Wisteria
    # 显示在页脚右侧的链接
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/wsh-zju/blog
# 文章相关配置
article:
    font_family: 'ZCOOL XiaoWei'
    # 代码高亮设置
    highlight:
        theme: atom-one-light   # 代码高亮主题
        clipboard: true # 显示复制代码按钮
        fold: unfolded  # 代码块的默认折叠状态
    readtime: true      # 显示阅读时间
    update_time: true   # 显示更新时间
    # 文章许可协议模块
    licenses:
        知识共享:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        署名:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        非商业性使用:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
# 搜索插件配置
search:
    type: insight
    index_pages: true   # 是否在搜索结果中包含页面
# 评论插件配置
comment:
    type: giscus
    repo: wsh-zju/blog
    repo_id: R_kgDORh7QKg         # Giscus 官网生成的 ID
    category: General      # 建议设为 Announcements 或 General
    category_id: DIC_kwDORh7QKs4C4Anb    # Giscus 官网生成的 ID
    mapping: pathname              # 评论映射方式，推荐 pathname
    reactions_enabled: 1           # 开启表情反馈
    emit_metadata: 0
    input_position: bottom         # 评论框位置
    lang: zh-CN                    # 语言设置为中文
    theme: preferred_color_scheme  # 自动跟随系统主题


    #<script src="https://giscus.app/client.js"
    #        data-repo="wsh-zju/blog"
    #        data-repo-id="R_kgDORh7QKg"
    #        data-category="General"
    #        data-category-id="DIC_kwDORh7QKs4C4Anb"
    #        data-mapping="pathname"
    #        data-strict="1"
    #        data-reactions-enabled="1"
    #        data-emit-metadata="0"
    #        data-input-position="bottom"
    #        data-theme="preferred_color_scheme"
    #        data-lang="zh-CN"
    #        crossorigin="anonymous"
    #        async>
    #</script>
donates:
    -
        type: alipay
        qrcode: /images/alipay.jpg
    -
        type: wechat
        qrcode: /images/wechat.png
# 分享插件配置
share:
    type: false
# 侧边栏配置
sidebar:
    left:
        sticky: true
    right:
        sticky: true
# 侧边栏组件配置
widgets:
    # 个人资料组件配置
    -
        position: left
        type: profile
        author: Lucy Wisteria
        author_title: Blog
        location: Zhejiang, China
        avatar: /images/logo.png
        avatar_rounded: true
        gravatar: 
        follow_link: https://github.com/wsh-zju
        # 个人资料组件底部的社交链接
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/wsh-zju
            Notebook:
                icon: fas fa-book
                url: https://wsh-zju.github.io/notebook/
    # 文章目录组件配置
    -
        position: right
        type: toc
        index: true
        collapsed: true
        depth: 3
    # 友情链接组件配置
    -
        position: left
        type: links
        links:
            Hexo: https://hexo.io
            Bulma: https://bulma.io
    # 文章分类组件配置
    -
        position: right
        type: categories
    -
        position: right
        type: recent_posts
    # 文章归档组件配置：按月份
    -
        position: right
        type: archives
    # 标签组件配置
    -
        position: right
        type: tags
        order_by: name
        amount: 
        show_count: true
    # Follow.it 邮件订阅组件配置
    -
        position: left
        type: followit
        description: 
        action_url: ''
        verification_code: ''
# 插件配置
plugins:
    animejs: true       # 启用页面启动动画
    back_to_top: true   # 显示“回到顶部”按钮
    gallery: true       # 启用图片画廊
    google_analytics:
        tracking_id: G-2C17YF7K0L
    katex: true
    mathjax: false
    outdated_browser: true
    pjax: true
    progressbar: true

# CDN 提供商设置
providers:
    cdn: jsdelivr
    font: google
    iconcdn: fontawesome