title: Lucy Wisteria's Blog
description: Welcome to Lucy Wisteria's Blog!
url: "https://wsh-zju.github.io/blog/"  # 替换为你的 GitHub Pages 地址
baseurl: "https://github.com/wsh-zju/blog"  

# 主题配置
theme: minima
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Markdown 解析
markdown: kramdown
kramdown:
  input: GFM  # 支持 GitHub Flavored Markdown
  syntax_highlighter: rouge

defaults:
  - scope:
      path: "" # 所有
    values:
      layout: default
      comments: true # 默认开启评论
  
# 分页配置
paginate: 5
paginate_path: "/blog/page:num/"

# SEO 优化
seo:
  title: true
  description: true
  image: "/assets/logo.png"

# 作者信息
author:
  name: "Lucy Wisteria"
  email: "2107633734@qq.com"
  wechat: "18103573921"


sass:
  sass_dir: assets/css
  style: compressed
  
# 归档配置
jekyll-archives:
  enabled: true
  layouts:
    year: archive_year
    month: archive_month
    day: archive_day
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    day: '/archives/:year/:month/:day/'