# 站点设置
title: Lucy Wisteria's Blog
subtitle: 'Computer Sciences & Engineering'
description: '记录算法、架构与工程实践的个人知识库'
author: Lucy Wisteria
language: zh-CN
timezone: 'Asia/Shanghai'
theme: icarus

url: https://wsh-zju.github.io/blog/
root: /blog/
permalink: :year/:month/:day/:title/ # 这种结构最利于 SEO

index_generator:
  path: ''
  per_page: 10 # 首页文章数
  order_by: -date # 按时间倒序

# Deployment
deploy:
  type: git
  repo: https://github.com/wsh-zju/blog.git
  branch: gh-pages

comment:
  type: true