name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          # 确保主题目录下的依赖也已安装
          [ -d "themes/icarus"] && cd themes/icarus && npm install 

      - name: Generate site
        run: |
            npx hexo clean
            npx hexo generate
    
      - name: List files for debug
        run: ls -R public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public